on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 4 PM UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  widoco:
    runs-on: ubuntu-latest
    name: A conversion of ttl to html
    steps:
      - name: convert
        uses: soilwise-he/widoco-action@v0.3
        with:
          file-input: '/github/workspace/vivo.owl'
          folder-output: '/github/workspace/vivo.owl'
          options: '-excludeProvenance -getOntologyMetadata'
