jobs:
  widoco:
    runs-on: ubuntu-latest
    name: A conversion of ttl to html
    steps:
      - name: convert
        uses: soilwise-he/widoco-action@v0.3
        with:
          file-input: '/github/workspace/example.ttl'
          folder-output: '/github/workspace/public'
          options: '-excludeProvenance -getOntologyMetadata'
